// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0VFTTb62Vu_fhUBWVVbaVa0jMfv20uF4',
    appId: '1:1035917486333:web:1e422b8268fc1c8b617694',
    messagingSenderId: '1035917486333',
    projectId: 'shoppingonline-57e3c',
    authDomain: 'shoppingonline-57e3c.firebaseapp.com',
    storageBucket: 'shoppingonline-57e3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTkn37fvWHEQQaIrUiyIb0OqA02PhopE',
    appId: '1:1035917486333:android:caa2ca036bc45fd4617694',
    messagingSenderId: '1035917486333',
    projectId: 'shoppingonline-57e3c',
    storageBucket: 'shoppingonline-57e3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Q78mrWbCcVh__M6ScfVRh-P2ynGkV8I',
    appId: '1:1035917486333:ios:9ff4ecdff4c409eb617694',
    messagingSenderId: '1035917486333',
    projectId: 'shoppingonline-57e3c',
    storageBucket: 'shoppingonline-57e3c.firebasestorage.app',
    iosBundleId: 'com.masterung.shoppingonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Q78mrWbCcVh__M6ScfVRh-P2ynGkV8I',
    appId: '1:1035917486333:ios:9ff4ecdff4c409eb617694',
    messagingSenderId: '1035917486333',
    projectId: 'shoppingonline-57e3c',
    storageBucket: 'shoppingonline-57e3c.firebasestorage.app',
    iosBundleId: 'com.masterung.shoppingonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0VFTTb62Vu_fhUBWVVbaVa0jMfv20uF4',
    appId: '1:1035917486333:web:1667fa8a9aceda72617694',
    messagingSenderId: '1035917486333',
    projectId: 'shoppingonline-57e3c',
    authDomain: 'shoppingonline-57e3c.firebaseapp.com',
    storageBucket: 'shoppingonline-57e3c.firebasestorage.app',
  );
}
